import {
  Braces,
  Binary,
  Fingerprint,
  Palette,
  Database,
  FileCode2,
  Link2,
  Ampersand,
  Type,
  KeyRound,
  KeySquare,
  Blend,
  GitCompare,
  CaseSensitive,
  Clock,
  Hash,
  Regex,
  WholeWord,
  Timer,
  ArrowLeftRight,
  Eye,
  Wand2,
  FileJson2,
  Shield,
  ArrowRightLeft,
  FileImage,
  SquareCode,
  QrCode,
  ShieldCheck,
  FileSpreadsheet,
  FileCode,
  Image,
  SwatchBook,
  FileDiff,
  Table2,
  Terminal,
  Sheet,
  Lock,
  Dices,
  Link,
  Globe,
  MonitorSmartphone,
  FileKey,
  Table,
  type LucideIcon,
} from "lucide-react";

export type ToolCategoryId =
  | "formatters"
  | "encoders"
  | "generators"
  | "colors"
  | "text";

export interface ToolCategory {
  id: ToolCategoryId;
  name: string;
  description: string;
  icon: LucideIcon;
}

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: ToolCategoryId;
  href: string;
  /** Search keywords beyond name/description, used by the command palette. */
  keywords?: string[];
  /** Surfaced with a "Popular" badge on the homepage. */
  popular?: boolean;
  /** Listed in the catalog (mega-menu, homepage) but not yet built. */
  comingSoon?: boolean;
}

export const toolCategories: ToolCategory[] = [
  {
    id: "formatters",
    name: "Formatters",
    description: "Format, validate, and beautify structured data.",
    icon: Braces,
  },
  {
    id: "encoders",
    name: "Encoders",
    description: "Encode and decode data between formats.",
    icon: Binary,
  },
  {
    id: "generators",
    name: "Generators",
    description: "Generate IDs, tokens, and other dev artifacts.",
    icon: Fingerprint,
  },
  {
    id: "colors",
    name: "Colors",
    description: "Inspect, convert, and preview colors.",
    icon: Palette,
  },
  {
    id: "text",
    name: "Text",
    description: "Compare, transform, and clean up text.",
    icon: Type,
  },
];

export const tools: Tool[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, minify, and validate JSON with a Monaco editor.",
    icon: Braces,
    category: "formatters",
    href: "/tools/json-formatter",
    keywords: ["json", "beautify", "minify", "validate", "pretty print"],
    popular: true,
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Format and validate XML documents.",
    icon: FileCode2,
    category: "formatters",
    href: "/tools/xml-formatter",
    keywords: ["xml", "format", "validate", "pretty print"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify SQL queries with consistent indentation.",
    icon: Database,
    category: "formatters",
    href: "/tools/sql-formatter",
    keywords: ["sql", "query", "format", "mysql", "postgres"],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode and decode Base64 strings instantly.",
    icon: Binary,
    category: "encoders",
    href: "/tools/base64-encoder",
    keywords: ["base64", "encode", "decode"],
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Encode special characters for URLs or decode them back.",
    icon: Link2,
    category: "encoders",
    href: "/tools/url-encoder",
    keywords: ["url", "uri", "encode", "decode", "percent"],
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    description: "Encode and decode HTML entity characters.",
    icon: Ampersand,
    category: "encoders",
    href: "/tools/html-entities",
    keywords: ["html", "entities", "escape", "unescape"],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate v4 UUIDs in bulk.",
    icon: Fingerprint,
    category: "generators",
    href: "/tools/uuid-generator",
    keywords: ["uuid", "guid", "id", "generate"],
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder text, paragraphs, or words.",
    icon: Type,
    category: "generators",
    href: "/tools/lorem-ipsum",
    keywords: ["lorem ipsum", "placeholder", "dummy text"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords.",
    icon: KeyRound,
    category: "generators",
    href: "/tools/password-generator",
    keywords: ["password", "generate", "random", "secure"],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, and HSL color formats.",
    icon: Palette,
    category: "colors",
    href: "/tools/color-converter",
    keywords: ["color", "hex", "rgb", "hsl", "convert"],
  },
  {
    id: "gradient-generator",
    name: "Gradient Generator",
    description: "Design and preview CSS gradients.",
    icon: Blend,
    category: "colors",
    href: "/tools/gradient-generator",
    keywords: ["gradient", "css", "linear", "radial"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two texts side by side.",
    icon: GitCompare,
    category: "text",
    href: "/tools/text-diff",
    keywords: ["diff", "compare", "text", "changes"],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between case styles.",
    icon: CaseSensitive,
    category: "text",
    href: "/tools/case-converter",
    keywords: ["case", "camelcase", "snake_case", "kebab-case", "title case"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test a regular expression against sample text with live match highlighting.",
    icon: Regex,
    category: "text",
    href: "/tools/regex-tester",
    keywords: ["regex", "regexp", "regular expression", "match", "pattern"],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode a JWT's header and payload, and verify HMAC signatures.",
    icon: KeySquare,
    category: "encoders",
    href: "/tools/jwt-decoder",
    keywords: ["jwt", "json web token", "decode", "verify", "hmac"],
    popular: true,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix epoch timestamps to and from human-readable dates.",
    icon: Clock,
    category: "encoders",
    href: "/tools/timestamp-converter",
    keywords: ["timestamp", "epoch", "unix", "date", "time", "convert"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes of text or a file.",
    icon: Hash,
    category: "generators",
    href: "/tools/hash-generator",
    keywords: ["hash", "md5", "sha1", "sha256", "sha512", "checksum", "digest"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and sentences. Reading time and word frequency analysis.",
    icon: WholeWord,
    category: "text",
    href: "/tools/word-counter",
    keywords: ["word count", "character count", "reading time", "text stats"],
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, and hexadecimal. BigInt support.",
    icon: ArrowRightLeft,
    category: "encoders",
    href: "/tools/number-base-converter",
    keywords: ["binary", "octal", "decimal", "hexadecimal", "base convert", "radix"],
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Interactive Linux permission calculator. Octal ↔ symbolic, common presets, chmod commands.",
    icon: Shield,
    category: "encoders",
    href: "/tools/chmod-calculator",
    keywords: ["chmod", "permissions", "octal", "symbolic", "linux", "unix", "rwx"],
  },
  {
    id: "binary-to-text",
    name: "Binary to Text",
    description: "Convert between text and binary, hex, octal, decimal. ASCII reference table included.",
    icon: SquareCode,
    category: "encoders",
    href: "/tools/binary-to-text",
    keywords: ["binary", "ascii", "hex", "octal", "decimal", "convert", "bytes"],
  },
  {
    id: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Convert JSON to TypeScript interfaces and types. Nested objects, arrays, optional fields.",
    icon: FileJson2,
    category: "formatters",
    href: "/tools/json-to-typescript",
    keywords: ["json", "typescript", "interface", "type", "codegen"],
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    description: "Validate JSON, find errors with line numbers, and analyze structure in real-time.",
    icon: ShieldCheck,
    category: "formatters",
    href: "/tools/json-validator",
    keywords: ["json", "validate", "lint", "syntax error", "structure"],
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON arrays to CSV format. Custom delimiters, download as .csv file.",
    icon: FileSpreadsheet,
    category: "formatters",
    href: "/tools/json-to-csv",
    keywords: ["json", "csv", "convert", "spreadsheet", "export"],
  },
  {
    id: "yaml-json-converter",
    name: "YAML ↔ JSON Converter",
    description: "Convert between YAML and JSON instantly. Supports Kubernetes, Docker Compose, GitHub Actions.",
    icon: ArrowLeftRight,
    category: "formatters",
    href: "/tools/yaml-json-converter",
    keywords: ["yaml", "json", "convert", "kubernetes", "docker compose", "github actions"],
  },
  {
    id: "css-minifier",
    name: "CSS Minifier & Beautifier",
    description: "Minify CSS for production or beautify for readability. Shows size savings and stats.",
    icon: Wand2,
    category: "formatters",
    href: "/tools/css-minifier",
    keywords: ["css", "minify", "beautify", "format", "compress"],
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview Markdown in real-time. GFM, tables, code blocks. Export to HTML.",
    icon: Eye,
    category: "text",
    href: "/tools/markdown-preview",
    keywords: ["markdown", "preview", "gfm", "render", "html"],
  },
  {
    id: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to clean Markdown. Headings, links, images, tables, code blocks.",
    icon: FileCode,
    category: "formatters",
    href: "/tools/html-to-markdown",
    keywords: ["html", "markdown", "convert", "turndown"],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create QR codes for text, URLs, email, WiFi, phone. Custom colors. Download PNG/SVG.",
    icon: QrCode,
    category: "generators",
    href: "/tools/qr-code-generator",
    keywords: ["qr code", "qr", "generate", "wifi", "email", "url"],
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Encode images to Base64 data URIs. Decode Base64 back to images. HTML & CSS snippets.",
    icon: FileImage,
    category: "encoders",
    href: "/tools/image-to-base64",
    keywords: ["image", "base64", "data uri", "encode", "decode"],
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG to high-quality PNG. Custom scale (1x-4x), transparent background.",
    icon: Image,
    category: "generators",
    href: "/tools/svg-to-png",
    keywords: ["svg", "png", "convert", "export", "raster"],
  },
  {
    id: "cron-generator",
    name: "Cron Expression Generator",
    description: "Build, parse, and explain cron schedules. See next execution times. Crontab guru alternative.",
    icon: Timer,
    category: "generators",
    href: "/tools/cron-generator",
    keywords: ["cron", "crontab", "schedule", "expression", "job"],
  },
  {
    id: "tailwind-colors",
    name: "Tailwind Colors",
    description: "Full Tailwind CSS palette with live component previews. Pick, preview, copy.",
    icon: SwatchBook,
    category: "colors",
    href: "/tools/tailwind-colors",
    keywords: ["tailwind", "colors", "palette", "css", "swatches"],
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON documents key by key.",
    icon: FileDiff,
    category: "formatters",
    href: "/tools/json-diff",
    keywords: ["json", "diff", "compare", "changes"],
  },
  {
    id: "mock-data-generator",
    name: "Mock Data Generator",
    description: "Generate fake JSON or CSV data from a field schema.",
    icon: Table2,
    category: "generators",
    href: "/tools/mock-data-generator",
    keywords: ["mock", "fake data", "test data", "seed", "faker"],
  },
  {
    id: "curl-command-builder",
    name: "curl Command Builder",
    description: "Build a curl command from method, headers, and body — or paste one to break it apart.",
    icon: Terminal,
    category: "generators",
    href: "/tools/curl-command-builder",
    keywords: ["curl", "http", "request", "api", "command"],
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data to a JSON array of objects.",
    icon: Sheet,
    category: "formatters",
    href: "/tools/csv-to-json",
    keywords: ["csv", "json", "convert", "import"],
  },
  {
    id: "jwt-encoder",
    name: "JWT Encoder",
    description: "Build and sign a JWT from a header and payload.",
    icon: Lock,
    category: "encoders",
    href: "/tools/jwt-encoder",
    keywords: ["jwt", "json web token", "encode", "sign", "hmac"],
  },
  {
    id: "nanoid-generator",
    name: "Nanoid/ULID Generator",
    description: "Generate Nanoid or ULID identifiers in bulk.",
    icon: Dices,
    category: "generators",
    href: "/tools/nanoid-generator",
    keywords: ["nanoid", "ulid", "id", "generate"],
  },
  {
    id: "slugify",
    name: "Slugify",
    description: "Convert text into a URL-safe slug.",
    icon: Link,
    category: "text",
    href: "/tools/slugify",
    keywords: ["slug", "slugify", "url", "kebab-case"],
  },
  {
    id: "http-status-lookup",
    name: "HTTP Status Code Lookup",
    description: "Look up the meaning of an HTTP status code.",
    icon: Globe,
    category: "encoders",
    href: "/tools/http-status-lookup",
    keywords: ["http", "status", "code", "lookup"],
  },
  {
    id: "user-agent-parser",
    name: "User-Agent Parser",
    description: "Parse a User-Agent string into browser, OS, and device details.",
    icon: MonitorSmartphone,
    category: "encoders",
    href: "/tools/user-agent-parser",
    keywords: ["user agent", "browser", "os", "device", "parse"],
  },
  {
    id: "env-converter",
    name: ".env Converter",
    description: "Convert between .env, JSON, and YAML formats.",
    icon: FileKey,
    category: "formatters",
    href: "/tools/env-converter",
    keywords: ["env", "dotenv", "json", "yaml", "environment variables"],
  },
  {
    id: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Build a Markdown table from rows and columns.",
    icon: Table,
    category: "generators",
    href: "/tools/markdown-table-generator",
    keywords: ["markdown", "table", "generate"],
  },
];

export function getToolsByCategory(category: ToolCategoryId): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getCategoryById(id: ToolCategoryId): ToolCategory | undefined {
  return toolCategories.find((category) => category.id === id);
}
